@echo off
echo Staging changes...
git add .
echo Committing changes...
git commit -m "Add Admin Dashboard, Serverless API, and dynamic slideshow features"
echo Pushing to GitHub...
git push
echo Done!
pause
